### PR TITLE
Add test for PR #500

### PR DESCRIPTION
**Pull request by jodavies**
Also overlooked in PR: align the warning messages from the two cases.

### CODE REVIEW

**Comment by jodavies** [comment]
By the way: I think it is OK to delete all of the branches from these merged PRs? There are quite a few in the repository now.

**Review by tueda — COMMENTED** [review]
Thanks! I will merge it.

**Comment by tueda** [comment]
To confirm, did you choose `expr` instead of `expression` just because of brevity? Or because the `warning?` method didn't work with long lines where newline characters are inserted? If it is the latter case, #504 provides the solution.

**Comment by jodavies** [comment]
For brevity. I thought it better if it is more likely to fit on one line. Of course if you change the width or have sufficiently long expression names there will be linebreaks anyway.

**Comment by tueda** [comment]
OK, then I will merge it (and then #504; there should be no more oversights in `warnings?` etc., I hope).

**Pull request merged**
